name: Release

on:
  workflow_call:
    inputs:
      runs_on:
        default: ubuntu-latest
        required: false
        type: string
      name:
        default: Generate a changelog
        required: false
        type: string
      cliff_args:
        default: -vv --latest --strip header
        required: false
        type: string
    secrets:
      gh_token:
        required: true

jobs:
    changelog:
      name: ${{ inputs.name }}
      runs-on: ${{ inputs.runs_on }}
      outputs:
        release_body: ${{ steps.git-cliff.outputs.content }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - name: ${{ inputs.name }}
          uses: orhun/git-cliff-action@v4
          id: git-cliff
          with:
            config: cliff.toml
            args: ${{ imputs.cliff_args }}
          env:
            OUTPUT: CHANGELOG.md
            GITHUB_REPO: ${{ github.repository }}
  
        - name: Upload the binary releases
          uses: svenstaro/upload-release-action@v2
          with:
            file: binary_release.zip
            repo_token: ${{ secrets.gh_token }}
            tag: ${{ github.ref }}
            body: ${{ steps.git-cliff.outputs.content }}
  
    upload:
      name: Upload the release
      needs: changelog
      runs-on: ${{ inputs.runs_on }}
      steps:
        - name: Upload the binary releases
          uses: svenstaro/upload-release-action@v2
          with:
            file: binary_release.zip
            repo_token: ${{ secrets.gh_token }}
            tag: ${{ github.ref }}
            body: ${{ needs.changelog.outputs.release_body }}
