name: Docker build and push

on:
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      name:
        default: codacy-security-scan
        required: false
        type: string
      context:
        default: ""
        required: true
        type: string
      file:
        default: ""
        required: true
        type: string
      image_name:
        default: ""
        required: true
        type: string
      push:
        default: true
        required: false
        type: boolean
      login_version:
        default: v3.0.0
        required: false
        type: string
      build_version:
        default: v3.0.0
        required: false
        type: string
      push_version:
        default: v5
        required: false
        type: string
    secrets:
      docker_user:
        required: true
      docker_token:
        required: true

permissions:
  contents: read

jobs:
  build_and_push:
    name: ${{ inputs.name }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Login to Docker Hub
        uses: docker/login-action@${{ inputs.login_version }}
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_token }}
  
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@${{ inputs.build_version }}
  
      - name: Build main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@${{ inputs.push_version }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name}}:latest
  
      - name: Build develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@${{ inputs.push_version }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name}}:develop
  
      - name: Build release
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@${{ inputs.push_version }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name}}:${{ github.ref_name }}
