## https://github.com/marketplace/actions/telegram-message-action
name: Send Telegram Message

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to send'
        required: false
        type: string
      runs-on:
        description: 'Runs on'
        required: false
        type: string
      name:
        description: 'Name'
        required: false
        type: string
    secrets:
      envTOKEN:
        description: 'Telegram Bot Token'
        required: true
        type: string
      envCHAT_ID:
        description: 'Telegram Chat ID'
        required: true
        type: number

jobs:
  telegram_notification:
    runs-on: ${{ inputs.runs-on }}
    name: ${{ inputs.name }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ inputs.name }}
        uses: cbrgm/telegram-github-action@v1.0.9
        with:
          to: ${{ secrets.envCHAT_ID }}
          token: ${{ secrets.envTOKEN }}
          message: ${{ inputs.message }}