## https://github.com/marketplace/actions/telegram-message-action
name: Send Telegram Message

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to send'
        required: false
        type: string
      runs-on:
        description: 'Runs on'
        required: false
        type: string
      name:
        description: 'Name'
        required: false
        type: string
    secrets:
      envTO:
        required: true
      envTOKEN:
        required: true

jobs:
  telegram_notification:
    if: always()
    runs-on: ${{ inputs.runs-on }}
    name: ${{ inputs.name }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ inputs.name }}
        uses: appleboy/telegram-action@v1.0.0
        with:
          to: ${{ secrets.envTO }}
          token: ${{ secrets.envTOKEN }}
          message: ${{ inputs.message }}
